AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to deploy an Aurora MySQL instance for BookStack

Parameters:
  ResourcePrefix:
    Type: String
    Default: BookStack
    Description: Prefix to use for all resource names

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID

  RDSSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: SSM parameter for the first subnet ID for RDS
  
  RDSSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: SSM parameter for the second subnet ID for RDS

  DatabaseName:
    Type: String
    Default: bookstack
    AllowedPattern: ^[a-zA-Z0-9_]+$
    Description: Name of the database schema

  DBInstanceClass:
    Type: String
    Default: db.t4g.medium
    AllowedValues:
      - db.t4g.medium
      - db.t4g.large
      - db.t3.medium
      - db.t3.large
      - db.r5.large
      - db.r5.xlarge
      - db.r6g.large
      - db.r6g.xlarge
      - db.r7g.large
    Description: Aurora MySQL instance class

  SecurityGroupId:
    Type: String
    Description: SSM parameter for the security group ID to be used by the RDS instance

  DBSecretName:
    Type: String
    Description: The ARN of the secret for the database password

  BackupTagKey:
    Type: String
    Description: They tag key used to apply a backup policy to the database for AWS Backups
    Default: backup-plan

  BackupTagValue:
    Type: String
    Description: The tag value of the backup tag
    Default: default

Resources:

  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Sub '${ResourcePrefix}-db-cluster'
      Engine: aurora-mysql
      EngineVersion: '8.0'
      DBClusterParameterGroupName: default.aurora-mysql8.0
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref DBSecretName, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref DBSecretName, ':SecretString:password}}' ]]
      DatabaseName: !Ref DatabaseName
      VpcSecurityGroupIds:
        - !Ref SecurityGroupId
      DBSubnetGroupName: !Ref DBSubnetGroup
      Tags:
        - Key: !Ref BackupTagKey
          Value: !Ref BackupTagValue
      
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub '${ResourcePrefix}'
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceClass: !Ref DBInstanceClass
      Engine: aurora-mysql
      PubliclyAccessible: false

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Aurora MySQL instance for !Ref ResourcePrefix
      SubnetIds:
        - !Ref RDSSubnet1
        - !Ref RDSSubnet2
        
Outputs:
  DBEndpoint:
    Description: The endpoint of the RDS database
    Value: !GetAtt DBCluster.Endpoint.Address
  DBPort:
    Description: The port of the RDS database
    Value: !GetAtt DBCluster.Endpoint.Port
  DBName:
    Description: The name of the RDS database
    Value: !Ref DatabaseName
  DBClusterName:
    Description: The ID of the RDS database cluster
    Value: !Ref DBCluster