AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to deploy an Application Load Balancer with TLS encryption

Parameters:
  ResourcePrefix:
    Type: String
    Default: cbdg-cd
    Description: Prefix for naming resources

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID

  LoadBalancerSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Subnets for the Load Balancer

  LoadBalancerSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Subnets for the Load Balancer

  ACMCertificateArn:
    Type: String
    Description: ARN of the ACM Certificate for the Load Balancer

  LoadBalancerSecurityGroup:
    Type: String
    Description: SSM Parameter for the Load Balancer Security Group ID

  LoadBalancerScheme:
    Type: String
    AllowedValues:
      - internal
      - internet-facing
    Default: internal
    Description: Scheme for the Load Balancer

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${ResourcePrefix}"
      Subnets:
        - !Ref LoadBalancerSubnet1
        - !Ref LoadBalancerSubnet2
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Scheme: !Ref LoadBalancerScheme
      Type: application
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'

  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref ACMCertificateArn
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06

  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: 443
            StatusCode: HTTP_301
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${ResourcePrefix}-ecs-app"
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPCId
      TargetType: ip
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      Matcher:
        HttpCode: '200-399'

Outputs:
  LoadBalancerName:
    Value: !GetAtt LoadBalancer.LoadBalancerName
    Description: Name of the Load Balancer resource

  TargetGroup:
    Value: !Ref TargetGroup