AWSTemplateFormatVersion: '2010-09-09'
Description: Parent CloudFormation template to create nested stacks for infrastructure deployment

Parameters:
  ResourcePrefix:
    Type: String
    Default: cbpg-bookstack
    Description: Prefix to use for all resources

  VPCId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::VPC::Id>
    Description: The VPC ID where the resources will be deployed
    Default: /devops/vpc-id

  CreateMonitoring:
    Type: String
    AllowedValues:
      - true
      - false
    Default: false
    Description: Enables or disables the creation of the monitoring stack

  AppDomain:
    Type: String
    Default: bookstack.iyadk.com
    Description: Application domain name used for ALB

  AppKey:
    Type: String
    Description: Application data encryption key used for data exports and migrations
    NoEcho: true
     
  AlarmSNSArn:
    Type: String
    Default: ""
    Description: SSM parameter for the ARN of the existing SNS topic to receive alarm notifications

  WebSubnet1:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Description: The SSM parameter for the load balancer subnet ID 
    Default: /devops/web-subnet-1

  WebSubnet2:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Description: The SSM parameter for the load balancer subnet ID
    Default: /devops/web-subnet-2

  AppSubnet1:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Description: The SSM parameter for the fargate service's subnet ID
    Default: /devops/app-subnet-1

  AppSubnet2:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Description: The SSM parameter for the fargate service's subnet ID
    Default: /devops/app-subnet-2

  DataSubnet1:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Description: The SSM parameter for the first subnet ID for RDS
    Default: /devops/data-subnet-1

  DataSubnet2:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Description: The SSM parameter for the second subnet ID for RDS
    Default: /devops/data-subnet-2
  
  ACMCertificateArn:
    Type: AWS::SSM::Parameter::Value<String>
    Description: The SSM parameter for the ACM Certificate ARN 
    Default: /devops/certificate

Conditions:
  CreateMonitoringStack:
    Fn::Equals:
      - !Ref CreateMonitoring
      - 'true'

Resources:
  sharedinfra:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: shared-infra.yml
      Parameters:
        ResourcePrefix: !Ref ResourcePrefix
        VPCId: !Ref VPCId

  database:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: database.yml
      Parameters:
        ResourcePrefix: !Ref ResourcePrefix
        VPCId: !Ref VPCId
        RDSSubnet1: !Ref DataSubnet1
        RDSSubnet2: !Ref DataSubnet2
        SecurityGroupId: !GetAtt sharedinfra.Outputs.DBSecurityGroup
        DBSecretName: !GetAtt sharedinfra.Outputs.DBSecretName

  frontend:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: frontend.yml
      Parameters:
        ResourcePrefix: !Ref ResourcePrefix
        VPCId: !Ref VPCId
        LoadBalancerSecurityGroup: !GetAtt sharedinfra.Outputs.LoadBalancerSecurityGroup
        LoadBalancerSubnet1: !Ref WebSubnet1
        LoadBalancerSubnet2: !Ref WebSubnet2
        ACMCertificateArn: !Ref ACMCertificateArn
        AppDomain: !Ref AppDomain

  app:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: app.yml
      Parameters:
        ResourcePrefix: !Ref ResourcePrefix
        VPCId: !Ref VPCId
        AppSecurityGroup: !GetAtt sharedinfra.Outputs.AppSecurityGroup
        EFSSecurityGroup: !GetAtt sharedinfra.Outputs.EFSSecurityGroup
        ECSTaskSubnetIds: !Sub '${AppSubnet1},${AppSubnet2}'
        ALBTargetGroupArn: !GetAtt frontend.Outputs.TargetGroupArn
        DatabaseHost: !GetAtt database.Outputs.DBEndpoint
        DatabasePort: !GetAtt database.Outputs.DBPort
        DatabaseName: !GetAtt database.Outputs.DBName
        DatabaseCredsSecret: !GetAtt sharedinfra.Outputs.DBSecretArn
        AppURL: !Sub "https://${AppDomain}"
        AppKey: !Ref AppKey
        LogGroupName: !GetAtt sharedinfra.Outputs.LogGroupName        

  monitoring:
    Type: AWS::CloudFormation::Stack
    Condition: CreateMonitoringStack
    Properties:
      TemplateURL: monitoring.yml
      Parameters:
        NamePrefix: !Ref ResourcePrefix
        AlarmSNSArn: !Ref AlarmSNSArn
        LoadBalancerArn: !GetAtt frontend.Outputs.LoadBalancerArn
        TargetGroupArn: !GetAtt frontend.Outputs.TargetGroupArn
        DBClusterName: !GetAtt database.Outputs.DBClusterName
        ECSServiceName: !GetAtt app.Outputs.ECSService
        ECSClusterName: !GetAtt app.Outputs.ECSCluster
        EFSFileSystemId: !GetAtt app.Outputs.EFSId

        