AWSTemplateFormatVersion: '2010-09-09'
Description: Parent CloudFormation template to create nested stacks for infrastructure deployment

Parameters:
  ResourcePrefix:
    Type: String
    Default: cbpg-bookstack
    Description: Prefix to use for all resources

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID where the resources will be deployed

  CreateMonitoring:
    Type: String
    AllowedValues:
      - true
      - false
    Default: false
    Description: Enables or disables the creation of the monitoring stack

  AlarmSNSArn:
    Type: String
    Default: None
    Description: SSM parameter for the ARN of the existing SNS topic to receive alarm notifications

  WebSubnet1:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Description: The SSM parameter for the load balancer subnet ID 
    Default: /devops/web-subnet-1

  WebSubnet2:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Description: The SSM parameter for the load balancer subnet ID
    Default: /devops/web-subnet-2

  AppSubnet1:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Description: The SSM parameter for the fargate service's subnet ID
    Default: /devops/app-subnet-1

  AppSubnet2:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Description: The SSM parameter for the fargate service's subnet ID
    Default: /devops/app-subnet-2

  DataSubnet1:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Description: The SSM parameter for the first subnet ID for RDS
    Default: /devops/data-subnet-1

  DataSubnet2:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Description: The SSM parameter for the second subnet ID for RDS
    Default: /devops/data-subnet-2
  
  ACMCertificateArn:
    Type: AWS::SSM::Parameter::Value<String>
    Description: The SSM parameter for the ACM Certificate ARN 
    Default: /devops/certificate

Conditions:
  CreateMonitoringStack:
    Fn::Equals:
      - !Ref CreateMonitoring
      - 'true'

Resources:
  sharedinfra:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: shared-infra.yml
      Parameters:
        ResourcePrefix: !Ref ResourcePrefix
        VPCId: !Ref VPCId

  database:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: database.yml
      Parameters:
        ResourcePrefix: !Ref ResourcePrefix
        VPCId: !Ref VPCId
        RDSSubnet1: !Ref DataSubnet1
        RDSSubnet2: !Ref DataSubnet2
        SecurityGroupId: !GetAtt sharedinfra.Outputs.DBSecurityGroup
        DBSecretArn: !GetAtt sharedinfra.Outputs.DBSecretArn

  frontend:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: frontend.yml
      Parameters:
        StackName: !Sub '${ResourcePrefix}-frontend'
        ResourcePrefix: !Ref ResourcePrefix
        VPCId: !Ref VPCId
        LoadBalancerSecurityGroup: !GetAtt sharedinfra.Outputs.LoadBalancerSecurityGroup
        LoadBalancerSubnet1: !Ref WebSubnet1
        LoadBalancerSubnet2: !Ref WebSubnet2
        ACMCertificateArn: !Ref ACMCertificateArn

  app:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${AWS::AccountId}-cloudformation-templates/app.yml"
      Parameters:
        StackName: !Sub '${ResourcePrefix}-app'
        ResourcePrefix: !Ref ResourcePrefix
        VPCId: !Ref VPCId
        AppSecurityGroup: !GetAtt sharedinfra.Outputs.AppSecurityGroup
        ECSTaskSubnetIds: !Sub '${AppSubnet1},${AppSubnet2}'
        ALBTargetGroupArn: !GetAtt frontend.Outputs.TargetGroup

  monitoring:
    Type: AWS::CloudFormation::Stack
    Condition: CreateMonitoringStack
    Properties:
      StackName: !Sub '${ResourcePrefix}-monitoring'
      TemplateURL: monitoring.yml
      Parameters:
        NamePrefix: !Ref ResourcePrefix
        AlarmSNSArn: !Ref AlarmSNSArn
        LoadBalancerName: !GetAtt frontend.Outputs.LoadBalancerName
        


