AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to monitor application availability, response time, and provide a CloudWatch Dashboard

Parameters:
  NamePrefix:
    Type: String
    Default: BookStack
    Description: Prefix for naming resources

  AlarmSNSArn:
    Type: String
    Description: ARN of the existing SNS topic to receive alarm notifications

  LoadBalancerName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: The SSM parameter for the ALB name

Resources:
  HTTPCheckAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${NamePrefix}-HTTP-Check-Alarm"
      AlarmDescription: "Alarm if the application is not available (HTTP 5xx errors)"
      Namespace: AWS/ApplicationELB
      MetricName: HTTPCode_Target_5XX_Count
      Dimensions:
        - Name: LoadBalancer
          Value: !Sub "app/${LoadBalancerName}"
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching

  TargetResponseTimeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${NamePrefix}-Response-Time-Alarm"
      AlarmDescription: "Alarm if the target response time exceeds 2 seconds"
      Namespace: AWS/ApplicationELB
      MetricName: TargetResponseTime
      Dimensions:
        - Name: LoadBalancer
          Value: !Sub "app/${NamePrefix}-alb/${LoadBalancerDNSName}"
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 2
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlarmSNSArn
      TreatMissingData: notBreaching

  CloudWatchDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub "${NamePrefix}-Dashboard"
      DashboardBody:
        Fn::Sub:
          - |
            {
              "widgets": [
                  "type": "metric",
                  "x": 0,
                  "y": 0,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "view": "timeSeries",
                    "stacked": false,
                    "metrics": [
                      [ "AWS/ApplicationELB", "RequestCount", "LoadBalancer", "${LoadBalancerName}", { "stat": "Sum"} ],
                      [ "AWS/ApplicationELB", "HTTPCode_Target_2XX_Count", "LoadBalancer", "${LoadBalancerName}", { "stat": "Sum"} ],
                      [ "AWS/ApplicationELB", "HTTPCode_Target_4XX_Count", "LoadBalancer", "${LoadBalancerName}", { "stat": "Sum"} ],
                      [ "AWS/ApplicationELB", "HTTPCode_Target_5XX_Count", "LoadBalancer", "${LoadBalancerName}", { "stat": "Sum"} ]
                    ],
                    "region": "${AWS::Region}",
                    "title": "ALB Request and Response Codes"
                  }
                },
                {
                  "type": "metric",
                  "x": 0,
                  "y": 6,
                  "width": 6,
                  "height": 6,
                  "properties": {
                    "view": "timeSeries",
                    "stacked": false,
                    "metrics": [
                      [ "AWS/ECS", "RunningTasksCount", "ClusterName", "${NamePrefix}-Cluster", { "stat": "Average"} ],
                      [ "AWS/ECS", "PendingTasksCount", "ClusterName", "${NamePrefix}-Cluster", { "stat": "Average"} ]
                    ],
                    "region": "${AWS::Region}",
                    "title": "ECS Running & Pending Tasks"
                  }
                },
                {
                  "type": "metric",
                  "x": 6,
                  "y": 6,
                  "width": 6,
                  "height": 6,
                  "properties": {
                    "view": "timeSeries",
                    "stacked": false,
                    "metrics": [
                      [ "AWS/ApplicationELB", "TargetResponseTime", "LoadBalancer", "${LoadBalancerName}", { "stat": "Average"} ]
                    ],
                    "region": "${AWS::Region}",
                    "title": "ALB Target Response Time"
                  },
                {
                  "type": "metric",
                  "x": 0,
                  "y": 12,
                  "width": 6,
                  "height": 6,
                  "properties": {
                    "view": "timeSeries",
                    "stacked": false,
                    "metrics": [
                      [ "AWS/ECS", "CPUUtilization", "ClusterName", "${NamePrefix}-Cluster", { "stat": "Average"} ],
                      [ ".", "ServiceName", "${NamePrefix}-service" ]
                    ],
                    "region": "${AWS::Region}",
                    "title": "ECS CPU Utilization"
                  }
                },
                {
                  "type": "metric",
                  "x": 6,
                  "y": 12,
                  "width": 6,
                  "height": 6,
                  "properties": {
                    "view": "timeSeries",
                    "stacked": false,
                    "metrics": [
                      [ "AWS/ECS", "MemoryUtilization", "ClusterName", "${NamePrefix}-Cluster", { "stat": "Average"} ],
                      [ ".", "ServiceName", "${NamePrefix}-service" ]
                    ],
                    "region": "${AWS::Region}",
                    "title": "ECS Memory Utilization"
                  }
                }
              ]
            }
          - {}
